apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
stringData:
  # DB URL: psql-<your-prefix>.postgres.database.azure.com
  # DB Username: nutritionadmin
  # DB Password: Nutrition123
  db_username: fsaadmin
  db_password: Nutrition123
  db_url: psql-fsa-kiiashchenkoi.postgres.database.azure.com

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
stringData:
  # Keycloak Username: admin
  # Keycloak Password: Nutrition123
  kc_username: admin
  kc_password: Nutrition123

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: infra
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
stringData:
  runner-registration-token: ""
  runner-token: "<fill-me>"

---

apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: Opaque
stringData:
  username: admin
  password: Nutrition123

---

apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: app
type: Opaque
stringData:
  # Replace with your actual OpenAI API key
  api_key: "<your-openai-api-key>"
